# Generated by Django 5.1.5 on 2025-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('callNumber', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('year_published', models.CharField(blank=True, max_length=10, null=True)),
                ('shelfNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('availability', models.CharField(default='Available', max_length=50)),
                ('timesBorrowed', models.IntegerField(default=0)),
                ('condition', models.CharField(default='Good', max_length=50)),
            ],
        ),
    ]
